import { rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { loadConfig } from '../core/config.js';
import { fileExists, readTextFile } from '../core/files.js';
import { icons, printPlanItem, printCallout, c } from '../core/ui.js';

interface RemoveOptions {
  yes?: boolean;
}

interface RemovePlan {
  path: string;
  action: 'delete' | 'strip-block';
  content?: string;
}

const START_MARKER = '<!-- specman:start -->';
const END_MARKER = '<!-- specman:end -->';

/**
 * Safely remove specman-managed files from the current repository.
 */
export async function removeCommand(root: string, options: RemoveOptions = {}): Promise<void> {
  const config = await loadConfig(root);
  const candidates = [
    config.specsDir,
    '.specman',
    '.specmanignore',
  ];
  const generatedInstructionFiles = [
    'SPECMAN.md',
    'CLAUDE.md',
    'CODEX.md',
    'AGENTS.md',
    '.cursor/rules/specman.mdc',
    '.github/copilot-instructions.md',
  ];

  const plans: RemovePlan[] = [];
  for (const candidate of candidates) {
    if (await fileExists(join(root, candidate))) {
      plans.push({ path: candidate, action: 'delete' });
    }
  }
  for (const candidate of generatedInstructionFiles) {
    const content = await readTextFile(join(root, candidate));
    if (!content) continue;

    const withoutBlocks = removeManagedBlocks(content).trim();
    if (withoutBlocks !== content.trim()) {
      if (withoutBlocks.length === 0) {
        plans.push({ path: candidate, action: 'delete' });
      } else {
        plans.push({ path: candidate, action: 'strip-block', content: `${withoutBlocks}\n` });
      }
      continue;
    }

    // Legacy detection: files generated before managed-block era
    if (content.startsWith('auto-generated by `specman')) {
      plans.push({ path: candidate, action: 'delete' });
      continue;
    }
  }

  if (plans.length === 0) {
    console.log(`  ${icons.info}  No specman-managed files found.`);
    return;
  }

  printCallout('info', [c.bold('Specman-managed files that would be removed:')]);
  for (const plan of plans) {
    const label = plan.action === 'strip-block' ? `${plan.path} ${c.dim('(remove specman block only)')}` : plan.path;
    printPlanItem(label, plan.action);
  }

  if (!options.yes) {
    console.log();
    console.log(`  ${icons.info}  No files were removed.`);
    console.log(`  Re-run with ${c.cyan('specman remove --yes')} to delete them.`);
    return;
  }

  for (const plan of plans) {
    const path = join(root, plan.path);
    if (plan.action === 'strip-block') {
      await writeFile(path, plan.content ?? '', 'utf-8');
    } else {
      await rm(path, { recursive: true, force: true });
    }
  }

  console.log();
  console.log(`  ${icons.success}  ${c.greenB(`Removed specman data from ${plans.length} path(s).`)}`);
  console.log();
}

function removeManagedBlocks(content: string): string {
  const pattern = new RegExp(`${escapeRegex(START_MARKER)}[\\s\\S]*?${escapeRegex(END_MARKER)}\\n?`, 'g');
  return content.replace(pattern, '').trimEnd();
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
