import { join } from 'node:path';
import { loadConfig, loadStatus } from '../core/config.js';
import { safeWriteFile } from '../core/files.js';
import { icons, withLoader } from '../core/ui.js';

/**
 * Generate AI tool instruction files.
 */
export async function syncCommand(root: string, target: string): Promise<void> {
  if (target !== 'all') {
    console.log(`${icons.error} Unknown sync target: "${target}". Use \`specman sync all\`.`);
    process.exit(1);
  }

  const config = await loadConfig(root);
  const status = await loadStatus(root);

  if (!status.initialized) {
    console.log(`${icons.error} specman has not been initialized. Run \`specman init\` first.`);
    process.exit(1);
  }

  const approvalNote = status.approved
    ? 'Specs have been reviewed and approved as source of truth.'
    : `${icons.warn} Specs have NOT been approved yet. Treat all specs as draft assumptions only.`;

  let generated = 0;

  await withLoader('Generating AI instructions', async () => {
    // ─── CLAUDE.md ───
    if (config.aiTools.claude) {
      const content = generateClaudeMd(config.specsDir, approvalNote);
      await safeWriteFile(join(root, 'CLAUDE.md'), content, true);
      console.log(`   ${icons.success} CLAUDE.md`);
      generated++;
    }

    // ─── AGENTS.md ───
    if (config.aiTools.agents) {
      const content = generateAgentsMd(config.specsDir, approvalNote);
      await safeWriteFile(join(root, 'AGENTS.md'), content, true);
      console.log(`   ${icons.success} AGENTS.md`);
      generated++;
    }

    // ─── .cursor/rules/specman.mdc ───
    if (config.aiTools.cursor) {
      const content = generateCursorRules(config.specsDir, approvalNote);
      await safeWriteFile(join(root, '.cursor', 'rules', 'specman.mdc'), content, true);
      console.log(`   ${icons.success} .cursor/rules/specman.mdc`);
      generated++;
    }

    // ─── .github/copilot-instructions.md ───
    if (config.aiTools.copilot) {
      const content = generateCopilotInstructions(config.specsDir, approvalNote);
      await safeWriteFile(join(root, '.github', 'copilot-instructions.md'), content, true);
      console.log(`   ${icons.success} .github/copilot-instructions.md`);
      generated++;
    }
  });

  console.log(`Generated ${generated} AI instruction file(s).`);

  if (!status.approved) {
    console.log(`\n${icons.warn} Specs are not yet approved. AI tools will treat them as assumptions.`);
    console.log('   Run `specman approve` to mark specs as source of truth.');
  }
}

// ─── Generator Functions ───

function coreInstructions(specsDir: string, approvalNote: string): string {
  return `## Project Specs

${approvalNote}

## Before Making Any Code Changes

1. **Read the specs directory** (\`${specsDir}/\`) to understand the project context.
2. **Check domain rules** in \`${specsDir}/domain/\` — these must NEVER be violated.
3. **Check ADRs** in \`${specsDir}/adr/\` — follow existing architecture decisions.
4. **Search solved cases** in \`${specsDir}/cases/\` before solving similar problems.

## Critical Rules

- Treat approved specs as the **source of truth**.
- Treat unapproved specs as **draft assumptions only** — verify with the developer.
- **Do NOT change architecture decisions** unless explicitly asked by the developer.
- **Do NOT violate domain rules** under any circumstances.
- If a request **conflicts with specs**, stop and explain the conflict before proceeding.
- If solving a meaningful issue, **suggest creating a solved case** after the fix.
- **Do NOT store secrets**, raw production logs, or PII in solved cases.

## Spec Structure

- \`${specsDir}/00-project-overview.md\` — Project overview
- \`${specsDir}/01-detected-stack.md\` — Technology stack
- \`${specsDir}/02-assumptions.md\` — Assumptions (check if approved)
- \`${specsDir}/03-open-questions.md\` — Open questions
- \`${specsDir}/product/\` — Product requirements
- \`${specsDir}/engineering/\` — Coding and testing rules
- \`${specsDir}/architecture/\` — System architecture and components
- \`${specsDir}/domain/\` — Business rules, workflows, decision tables, scenarios
- \`${specsDir}/adr/\` — Architecture Decision Records
- \`${specsDir}/cases/\` — Solved cases (previous problems and solutions)
- \`${specsDir}/ai/\` — AI-specific instructions, forbidden patterns, checklist`;
}

function generateClaudeMd(specsDir: string, approvalNote: string): string {
  return `# CLAUDE.md — Project Instructions for Claude

> This file was auto-generated by \`specman sync all\`. Do not edit manually.
> Regenerate with \`specman sync all\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Claude-Specific Instructions

- Read this entire file before starting any task.
- Summarize the relevant domain rules and ADRs before writing code.
- When in doubt about a domain rule, ask the developer rather than guessing.
- Prefer reading specs over inferring from code — specs are the source of truth.
`;
}

function generateAgentsMd(specsDir: string, approvalNote: string): string {
  return `# AGENTS.md — Project Instructions for AI Agents

> This file was auto-generated by \`specman sync all\`. Do not edit manually.
> Regenerate with \`specman sync all\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Agent-Specific Instructions

- Read the full spec directory before starting work.
- If you are unsure about a spec, ask the developer.
- Always verify your changes against domain rules.
- Run relevant tests after making changes.
`;
}

function generateCursorRules(specsDir: string, approvalNote: string): string {
  return `---
description: Project specs and rules managed by specman
globs:
  - "**/*"
alwaysApply: true
---

# Specman Project Rules

> This file was auto-generated by \`specman sync all\`. Do not edit manually.

${coreInstructions(specsDir, approvalNote)}

## Cursor-Specific Instructions

- Always read relevant spec files before suggesting code changes.
- Highlight any conflicts between requested changes and existing specs.
- Suggest updating specs when code changes affect architecture or domain rules.
`;
}

function generateCopilotInstructions(specsDir: string, approvalNote: string): string {
  return `# Copilot Instructions

> This file was auto-generated by \`specman sync all\`. Do not edit manually.
> Regenerate with \`specman sync all\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Copilot-Specific Instructions

- Prefer patterns that align with the project's coding rules.
- Follow the architecture described in specs.
- Do not suggest changes that violate domain rules.
`;
}
