import { dirname, join } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { loadConfig, loadStatus } from '../core/config.js';
import { ensureDir, readTextFile } from '../core/files.js';
import {
  icons,
  isInteractiveTerminal,
  withLoader,
  printSection,
  printPlanItem,
  printCallout,
  confirm,
  selectMenu,
  c,
} from '../core/ui.js';
import {
  detectAvailableAssistants,
  runAssistantNonInteractive,
  codeToSpecsPrompt,
  specsToCodePrompt,
  printManualPromptFallback,
  type AssistantCli,
} from '../core/ai.js';
import {
  generateSpecmanMd,
  generateClaudeMd,
  generateAgentsMd,
  generateCodexMd,
  generateCursorRules,
  generateCopilotInstructions,
} from '../core/templates.js';

interface SyncOptions {
  check?: boolean;
  yes?: boolean;
  /** Ask AI to update specs to match current code */
  codeToSpecs?: boolean;
  /** Ask AI to implement specs into code */
  specsToCode?: boolean;
}

interface SyncPlan {
  path: string;
  content: string;
  action: 'create' | 'replace-block' | 'append-block' | 'migrate-file' | 'unchanged';
  needsConfirmation: boolean;
}

const START_MARKER = '<!-- specman:start -->';
const END_MARKER = '<!-- specman:end -->';
const LEGACY_MARKER = 'auto-generated by `specman';

/**
 * Generate AI tool instruction files.
 */
export async function syncCommand(root: string, target: string, options: SyncOptions = {}): Promise<void> {
  // ── AI-powered sync directions ──────────────────────────────────────────
  if (options.codeToSpecs) {
    await syncWithAi(root, 'code-to-specs');
    return;
  }
  if (options.specsToCode) {
    await syncWithAi(root, 'specs-to-code');
    return;
  }

  if (target !== 'all') {
    console.log(`  ${icons.error}  Unknown sync target: "${target}". Use \`specman sync\`.`);
    process.exit(1);
  }

  const config = await loadConfig(root);
  const status = await loadStatus(root);

  if (!status.initialized) {
    console.log(`  ${icons.error}  specman has not been initialized. Run \`specman init\` first.`);
    process.exit(1);
  }

  const approvalNote = status.approved
    ? 'Specs have been reviewed and approved as source of truth.'
    : `${icons.warn} Specs have NOT been approved yet. Treat all specs as draft assumptions only.`;

  const plans: SyncPlan[] = [
    {
      path: 'SPECMAN.md',
      content: generateSpecmanMd(config.specsDir, approvalNote),
      action: 'create',
      needsConfirmation: false,
    },
  ];

  if (config.aiTools.claude) plans.push({ path: 'CLAUDE.md', content: generateClaudeMd(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.agents) plans.push({ path: 'AGENTS.md', content: generateAgentsMd(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.codex) plans.push({ path: 'CODEX.md', content: generateCodexMd(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.cursor) plans.push({ path: '.cursor/rules/specman.mdc', content: generateCursorRules(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.copilot) plans.push({ path: '.github/copilot-instructions.md', content: generateCopilotInstructions(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });

  const resolvedPlans = await Promise.all(plans.map(plan => resolveSyncPlan(root, plan)));

  if (options.check) {
    printSyncPlan(resolvedPlans);
    const hasChanges = resolvedPlans.some(plan => plan.action !== 'unchanged');
    if (hasChanges) process.exit(1);
    return;
  }

  const confirmationPlans = resolvedPlans.filter(plan => plan.needsConfirmation && plan.action !== 'unchanged');
  if (confirmationPlans.length > 0 && !options.yes) {
    printSyncPlan(confirmationPlans);
    if (!isInteractiveTerminal() || !(await confirm('Apply these changes?'))) {
      console.log(`\n  ${icons.info}  No files were changed.`);
      return;
    }
  }

  await withLoader('Generating AI instructions', async () => {
    for (const plan of resolvedPlans) {
      if (plan.action === 'unchanged') continue;
      await writeManagedFile(root, plan);
    }
  });

  const changed = resolvedPlans.filter(plan => plan.action !== 'unchanged').length;
  console.log(`  ${icons.success}  ${c.greenB(`Synced ${changed} AI instruction file(s).`)}`);

  if (!status.approved) {
    printCallout('warn', [
      'Specs are not yet approved — AI tools will treat them as draft assumptions.',
      `Run ${c.cyan('specman validate')} to review before treating as source of truth.`,
    ]);
  }
}

async function resolveSyncPlan(root: string, plan: SyncPlan): Promise<SyncPlan> {
  const filePath = join(root, plan.path);
  const existing = await readTextFile(filePath);
  const managedContent = wrapManagedBlock(plan.content);

  if (!existing) {
    return { ...plan, content: `${managedContent}\n`, action: 'create', needsConfirmation: false };
  }

  const blockMatches = existing.match(new RegExp(`${escapeRegex(START_MARKER)}[\\s\\S]*?${escapeRegex(END_MARKER)}`, 'g')) ?? [];
  if (blockMatches.length > 0) {
    const withoutBlocks = existing.replace(new RegExp(`${escapeRegex(START_MARKER)}[\\s\\S]*?${escapeRegex(END_MARKER)}\\n?`, 'g'), '').trimEnd();
    const nextContent = withoutBlocks ? `${withoutBlocks}\n\n${managedContent}\n` : `${managedContent}\n`;
    return {
      ...plan,
      content: nextContent,
      action: nextContent === existing ? 'unchanged' : 'replace-block',
      needsConfirmation: false,
    };
  }

  if (existing.includes(LEGACY_MARKER)) {
    return { ...plan, content: `${managedContent}\n`, action: 'migrate-file', needsConfirmation: false };
  }

  const nextContent = `${existing.trimEnd()}\n\n${managedContent}\n`;
  return { ...plan, content: nextContent, action: 'append-block', needsConfirmation: true };
}

function wrapManagedBlock(content: string): string {
  return `${START_MARKER}\n${content.trim()}\n${END_MARKER}`;
}

async function writeManagedFile(root: string, plan: SyncPlan): Promise<void> {
  const filePath = join(root, plan.path);
  await ensureDir(dirname(filePath));
  await writeFile(filePath, plan.content, 'utf-8');
}

// ─── AI-powered sync ──────────────────────────────────────────────────────────

async function syncWithAi(root: string, direction: 'code-to-specs' | 'specs-to-code'): Promise<void> {
  const config = await loadConfig(root);
  const status = await loadStatus(root);

  if (!status.initialized) {
    console.log(`  ${icons.error}  specman has not been initialized. Run ${c.cyan('specman init')} first.`);
    process.exit(1);
  }

  const specsDir = join(root, config.specsDir);
  const isWrite = true; // both directions modify files

  const label = direction === 'code-to-specs'
    ? 'Code → Specs  (AI reads code and updates your spec files)'
    : 'Specs → Code  (AI reads specs and updates your source code)';

  const prompt = direction === 'code-to-specs'
    ? codeToSpecsPrompt(specsDir)
    : specsToCodePrompt(specsDir);

  printSection(`AI Sync — ${label}`);

  // Detect available CLIs
  const available = await detectAvailableAssistants();

  if (available.length === 0) {
    printManualPromptFallback(prompt);
    return;
  }

  // Pick CLI
  let chosen: AssistantCli = available[0];
  if (available.length > 1) {
    chosen = await selectMenu(
      'Choose AI CLI',
      available.map((a, i) => ({ key: String(i + 1), label: a, value: a })),
      chosen,
    );
  } else {
    console.log(`  ${icons.info}  Using ${c.cyanB(chosen)}`);
  }

  // Warn about write access
  if (direction === 'specs-to-code') {
    printCallout('warn', [
      `${c.bold(chosen)} will be given ${c.yellowB('write access')} to your source code.`,
      'Review all changes carefully before committing.',
    ]);
  } else {
    printCallout('info', [
      `${c.bold(chosen)} will be given ${c.cyanB('write access')} to your ${c.cyan(config.specsDir + '/')} directory.`,
    ]);
  }

  if (isInteractiveTerminal()) {
    const ok = await confirm(`Run ${c.bold(chosen)} now?`);
    if (!ok) {
      console.log(`\n  ${icons.info}  Cancelled — no files were changed.`);
      return;
    }
  }

  await runAssistantNonInteractive(root, chosen, prompt, isWrite);
}


function printSyncPlan(plans: SyncPlan[]): void {
  printSection('Sync Plan');
  for (const plan of plans) {
    const note = plan.needsConfirmation ? 'requires confirmation' : '';
    printPlanItem(plan.path, plan.action, note);
  }
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
