import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { dirname, join } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { loadConfig, loadStatus } from '../core/config.js';
import { ensureDir, readTextFile } from '../core/files.js';
import { icons, isInteractiveTerminal, withLoader } from '../core/ui.js';

interface SyncOptions {
  check?: boolean;
  yes?: boolean;
}

interface SyncPlan {
  path: string;
  content: string;
  action: 'create' | 'replace-block' | 'append-block' | 'migrate-file' | 'unchanged';
  needsConfirmation: boolean;
}

const START_MARKER = '<!-- specman:start -->';
const END_MARKER = '<!-- specman:end -->';
const LEGACY_MARKER = 'auto-generated by `specman';

/**
 * Generate AI tool instruction files.
 */
export async function syncCommand(root: string, target: string, options: SyncOptions = {}): Promise<void> {
  if (target !== 'all') {
    console.log(`${icons.error} Unknown sync target: "${target}". Use \`specman sync\`.`);
    process.exit(1);
  }

  const config = await loadConfig(root);
  const status = await loadStatus(root);

  if (!status.initialized) {
    console.log(`${icons.error} specman has not been initialized. Run \`specman init\` first.`);
    process.exit(1);
  }

  const approvalNote = status.approved
    ? 'Specs have been reviewed and approved as source of truth.'
    : `${icons.warn} Specs have NOT been approved yet. Treat all specs as draft assumptions only.`;

  const plans: SyncPlan[] = [
    {
      path: 'SPECMAN.md',
      content: generateSpecmanMd(config.specsDir, approvalNote),
      action: 'create',
      needsConfirmation: false,
    },
  ];

  if (config.aiTools.claude) plans.push({ path: 'CLAUDE.md', content: generateClaudeMd(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.agents) plans.push({ path: 'AGENTS.md', content: generateAgentsMd(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.codex) plans.push({ path: 'CODEX.md', content: generateCodexMd(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.cursor) plans.push({ path: '.cursor/rules/specman.mdc', content: generateCursorRules(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });
  if (config.aiTools.copilot) plans.push({ path: '.github/copilot-instructions.md', content: generateCopilotInstructions(config.specsDir, approvalNote), action: 'create', needsConfirmation: false });

  const resolvedPlans = await Promise.all(plans.map(plan => resolveSyncPlan(root, plan)));

  if (options.check) {
    printSyncPlan(resolvedPlans);
    const hasChanges = resolvedPlans.some(plan => plan.action !== 'unchanged');
    if (hasChanges) process.exit(1);
    return;
  }

  const confirmationPlans = resolvedPlans.filter(plan => plan.needsConfirmation && plan.action !== 'unchanged');
  if (confirmationPlans.length > 0 && !options.yes) {
    printSyncPlan(confirmationPlans);
    if (!isInteractiveTerminal() || !(await confirmSync())) {
      console.log('No files were changed.');
      return;
    }
  }

  await withLoader('Generating AI instructions', async () => {
    for (const plan of resolvedPlans) {
      if (plan.action === 'unchanged') continue;
      await writeManagedFile(root, plan);
      console.log(`   ${icons.success} ${plan.path}`);
    }
  });

  const changed = resolvedPlans.filter(plan => plan.action !== 'unchanged').length;
  console.log(`Synced ${changed} AI instruction file(s).`);

  if (!status.approved) {
    console.log(`\n${icons.warn} Specs are not yet approved. AI tools will treat them as assumptions.`);
    console.log('   Review specs before treating them as source of truth.');
  }
}

async function resolveSyncPlan(root: string, plan: SyncPlan): Promise<SyncPlan> {
  const filePath = join(root, plan.path);
  const existing = await readTextFile(filePath);
  const managedContent = wrapManagedBlock(plan.content);

  if (!existing) {
    return { ...plan, content: `${managedContent}\n`, action: 'create', needsConfirmation: false };
  }

  const blockMatches = existing.match(new RegExp(`${escapeRegex(START_MARKER)}[\\s\\S]*?${escapeRegex(END_MARKER)}`, 'g')) ?? [];
  if (blockMatches.length > 0) {
    const withoutBlocks = existing.replace(new RegExp(`${escapeRegex(START_MARKER)}[\\s\\S]*?${escapeRegex(END_MARKER)}\\n?`, 'g'), '').trimEnd();
    const nextContent = withoutBlocks ? `${withoutBlocks}\n\n${managedContent}\n` : `${managedContent}\n`;
    return {
      ...plan,
      content: nextContent,
      action: nextContent === existing ? 'unchanged' : 'replace-block',
      needsConfirmation: false,
    };
  }

  if (existing.includes(LEGACY_MARKER)) {
    return { ...plan, content: `${managedContent}\n`, action: 'migrate-file', needsConfirmation: false };
  }

  const nextContent = `${existing.trimEnd()}\n\n${managedContent}\n`;
  return { ...plan, content: nextContent, action: 'append-block', needsConfirmation: true };
}

function wrapManagedBlock(content: string): string {
  return `${START_MARKER}\n${content.trim()}\n${END_MARKER}`;
}

async function writeManagedFile(root: string, plan: SyncPlan): Promise<void> {
  const filePath = join(root, plan.path);
  await ensureDir(dirname(filePath));
  await writeFile(filePath, plan.content, 'utf-8');
}

function printSyncPlan(plans: SyncPlan[]): void {
  console.log('specman sync plan:');
  for (const plan of plans) {
    console.log(`   ${icons.bullet} ${plan.path}: ${plan.action}${plan.needsConfirmation ? ' (requires confirmation)' : ''}`);
  }
}

async function confirmSync(): Promise<boolean> {
  const rl = createInterface({ input: stdin, output: stdout });
  try {
    const answer = (await rl.question('Apply these changes? [y/N] ')).trim().toLowerCase();
    return answer === 'y' || answer === 'yes';
  } finally {
    rl.close();
  }
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ─── Generator Functions ───

function generateSpecmanMd(specsDir: string, approvalNote: string): string {
  return `# SPECMAN.md — Project Spec Protocol

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

This repository uses specman to keep specs, architecture decisions, domain rules, solved cases, and AI instructions consistent.

${coreInstructions(specsDir, approvalNote)}

## How To Use Specman

- Run \`specman init\` once to create the spec structure and AI tool rules.
- Run \`specman sync\` after changing specs so AI tool rules stay current.
- Run \`specman validate\` before finalizing meaningful changes.
- Run \`specman validate --logic\` when logic-lock is configured.
- Create solved cases in \`${specsDir}/cases/\` after meaningful fixes.
`;
}

function coreInstructions(specsDir: string, approvalNote: string): string {
  return `## Project Specs

${approvalNote}

## Before Making Any Code Changes

1. **Read the specs directory** (\`${specsDir}/\`) to understand the project context.
2. **Check domain rules** in \`${specsDir}/domain/\` — these must NEVER be violated.
3. **Check ADRs** in \`${specsDir}/adr/\` — follow existing architecture decisions.
4. **Search solved cases** in \`${specsDir}/cases/\` before solving similar problems.

## Critical Rules

- Treat approved specs as the **source of truth**.
- Treat unapproved specs as **draft assumptions only** — verify with the developer.
- **Do NOT change architecture decisions** unless explicitly asked by the developer.
- **Do NOT violate domain rules** under any circumstances.
- If a request **conflicts with specs**, stop and explain the conflict before proceeding.
- If solving a meaningful issue, **suggest creating a solved case** after the fix.
- **Do NOT store secrets**, raw production logs, or PII in solved cases.

## Spec Structure

- \`${specsDir}/00-project-overview.md\` — Project overview
- \`${specsDir}/01-detected-stack.md\` — Technology stack
- \`${specsDir}/02-assumptions.md\` — Assumptions (check if approved)
- \`${specsDir}/03-open-questions.md\` — Open questions
- \`${specsDir}/product/\` — Product requirements
- \`${specsDir}/engineering/\` — Coding and testing rules
- \`${specsDir}/architecture/\` — System architecture and components
- \`${specsDir}/domain/\` — Business rules, workflows, decision tables, scenarios
- \`${specsDir}/adr/\` — Architecture Decision Records
- \`${specsDir}/cases/\` — Solved cases (previous problems and solutions)
- \`${specsDir}/ai/\` — AI-specific instructions, forbidden patterns, checklist

${caseCaptureProtocol(specsDir)}`;
}

function caseCaptureProtocol(specsDir: string): string {
  return `## Solved Case Capture Protocol

When you solve a meaningful problem, bug, incident, architecture issue, or recurring workflow issue, create a solved case file in \`${specsDir}/cases/\`.

Create a case when:
- The issue required non-obvious reasoning.
- The fix prevents a future regression.
- The solution documents a project-specific pattern.
- The work revealed a domain rule, architecture constraint, or operational lesson.

Do not create a case for:
- Trivial typo fixes.
- Pure formatting changes.
- Dependency bumps without behavior change.
- Temporary experiments.

Before writing the case:
1. Redact secrets, tokens, passwords, customer data, raw production logs, and PII.
2. Prefer summaries over raw logs.
3. Link related specs, ADRs, domain rules, tests, and changed files.

When reusing an existing case:
1. Prefer cases whose problem/context matches the current issue.
2. Increment \`Times Used\` when the case informed your approach.
3. Increment \`Successful Uses\` and \`Score\` when the case helped solve the problem.
4. Mention the reused case path in your final response.

Filename:
\`${specsDir}/cases/YYYY-MM-DD-kebab-case-title.md\`

Template:
\`\`\`md
# Case: <title>

## Status
Draft

## Usage
- Times Used: 0
- Successful Uses: 0
- Score: 0

## Problem
<What happened or what needed solving>

## Context
<Project-safe context only. No secrets, PII, or raw production logs.>

## Root Cause
<Why it happened>

## Solution
<What changed and why>

## Files Changed
- \`<path>\`: <short reason>

## Validation
- <test/check/build command and result>

## When To Reuse
<When this solution pattern applies>

## When NOT To Use
<When this solution would be wrong or risky>

## Related Specs
- \`${specsDir}/...\`

## Tags
<tag1>, <tag2>
\`\`\`

After creating the case:
- Mention the new case path in your final response.
- If unsure whether a case is worth creating, ask first.`;
}

function generateClaudeMd(specsDir: string, approvalNote: string): string {
  return `# CLAUDE.md — Project Instructions for Claude

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Claude-Specific Instructions

- Read this entire file before starting any task.
- Summarize the relevant domain rules and ADRs before writing code.
- When in doubt about a domain rule, ask the developer rather than guessing.
- Prefer reading specs over inferring from code — specs are the source of truth.
`;
}

function generateAgentsMd(specsDir: string, approvalNote: string): string {
  return `# AGENTS.md — Project Instructions for AI Agents

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Agent-Specific Instructions

- Read the full spec directory before starting work.
- If you are unsure about a spec, ask the developer.
- Always verify your changes against domain rules.
- Run relevant tests after making changes.
`;
}

function generateCodexMd(specsDir: string, approvalNote: string): string {
  return `# CODEX.md — Project Instructions for Codex

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Codex-Specific Instructions

- Read relevant spec files before implementing changes.
- Follow domain rules and ADRs strictly.
- Call out spec conflicts explicitly before proceeding.
- Suggest spec updates when behavior changes.
`;
}

function generateCursorRules(specsDir: string, approvalNote: string): string {
  return `---
description: Project specs and rules managed by specman
globs:
  - "**/*"
alwaysApply: true
---

# Specman Project Rules

> This file was auto-generated by \`specman sync\`. Do not edit manually.

${coreInstructions(specsDir, approvalNote)}

## Cursor-Specific Instructions

- Always read relevant spec files before suggesting code changes.
- Highlight any conflicts between requested changes and existing specs.
- Suggest updating specs when code changes affect architecture or domain rules.
`;
}

function generateCopilotInstructions(specsDir: string, approvalNote: string): string {
  return `# Copilot Instructions

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Copilot-Specific Instructions

- Prefer patterns that align with the project's coding rules.
- Follow the architecture described in specs.
- Do not suggest changes that violate domain rules.
`;
}
