import type { ScanResult, CaseData } from '../types.js';

// ─── Spec Templates ───

export function projectOverview(scan: ScanResult): string {
  const name = scan.projectName || 'Unnamed Project';
  const desc = scan.projectDescription || 'No description detected.';
  return `# Project Overview

## Name
${name}

## Description
${desc}

## Status
> ⚠️ DRAFT — This file was auto-generated by \`specman init\`. Review and update before approving.

## Goals
<!-- Describe the primary goals of this project -->

## Scope
<!-- Define what is in scope and out of scope -->

## Stakeholders
<!-- List key stakeholders -->
`;
}

export function detectedStack(scan: ScanResult): string {
  const stackLines = scan.detectedStack.length > 0
    ? scan.detectedStack.map(t => `- **${t.name}** (detected from \`${t.source}\`, confidence: ${t.confidence})`).join('\n')
    : '- No technologies detected. Please add manually.';

  const fileLines = scan.detectedFiles.length > 0
    ? scan.detectedFiles.map(f => `- \`${f}\``).join('\n')
    : '- No known files detected.';

  return `# Detected Stack

> ⚠️ DRAFT — Auto-detected by \`specman init\`. Verify and correct as needed.

## Technologies
${stackLines}

## Detected Files
${fileLines}

## Project Structure
- Has source code: ${scan.hasSrc ? 'Yes' : 'No'}
- Has tests: ${scan.hasTests ? 'Yes' : 'No'}
- Has Docker: ${scan.hasDocker ? 'Yes' : 'No'}
- Has CI/CD: ${scan.hasCi ? 'Yes' : 'No'}
- Has API spec: ${scan.hasApi ? 'Yes' : 'No'}
- Has migrations: ${scan.hasMigrations ? 'Yes' : 'No'}
`;
}

export function assumptions(scan: ScanResult): string {
  const stackAssumptions = scan.detectedStack
    .map(t => `- [ ] This project uses **${t.name}** (${t.confidence} confidence, source: \`${t.source}\`)`)
    .join('\n');

  return `# Assumptions

> ⚠️ DRAFT — These are auto-generated assumptions. Review each item and mark as confirmed or incorrect.

## Stack Assumptions
${stackAssumptions || '- No stack assumptions generated.'}

## Architecture Assumptions
- [ ] The project follows a standard structure for its stack
- [ ] There are no unusual build or deployment requirements
${scan.hasDocker ? '- [ ] Docker is used for containerized deployment' : ''}
${scan.hasCi ? '- [ ] CI/CD is configured via GitHub Actions' : ''}
${scan.hasMigrations ? '- [ ] Database migrations are managed in the migrations/ directory' : ''}

## Domain Assumptions
- [ ] Domain rules have not been formally documented yet
- [ ] Business logic is embedded in application code

## Risks
- [ ] Auto-detected assumptions may be wrong — verify before approving
- [ ] Missing context about deployment, scaling, and security requirements
`;
}

export function openQuestions(): string {
  return `# Open Questions

> ⚠️ DRAFT — Answer these questions to complete the spec.

## Architecture
- [ ] What is the deployment target? (cloud, on-prem, edge, etc.)
- [ ] Are there any external service dependencies?
- [ ] What is the expected scale/load?

## Domain
- [ ] What are the core business rules?
- [ ] Are there domain invariants that must never be violated?
- [ ] Are there edge cases that have caused bugs before?

## Engineering
- [ ] What coding standards does the team follow?
- [ ] What is the testing strategy?
- [ ] What is the release process?

## Security
- [ ] Are there authentication/authorization requirements?
- [ ] Are there data privacy requirements?
- [ ] Are there compliance requirements?
`;
}

// ─── Product Templates ───

export function productRequirements(): string {
  return `# Product Requirements

> ⚠️ DRAFT — Add your product requirements here.

## User Stories
<!-- Add user stories in the format: As a [role], I want [feature], so that [benefit] -->

## Acceptance Criteria
<!-- Define acceptance criteria for key features -->

## Non-Functional Requirements
<!-- Performance, security, accessibility, etc. -->
`;
}

// ─── Engineering Templates ───

export function codingRules(): string {
  return `# Coding Rules

> ⚠️ DRAFT — Define your team's coding standards here.

## General
- Write clear, readable code
- Follow the project's existing patterns
- Add comments for complex logic

## Naming Conventions
<!-- Define naming conventions for files, functions, variables, etc. -->

## Code Organization
<!-- Define how code should be organized -->

## Error Handling
<!-- Define error handling patterns -->
`;
}

export function testingRules(): string {
  return `# Testing Rules

> ⚠️ DRAFT — Define your team's testing standards here.

## Unit Tests
<!-- What should be unit tested? -->

## Integration Tests
<!-- What should be integration tested? -->

## Test Naming
<!-- How should tests be named? -->

## Coverage Requirements
<!-- Minimum coverage thresholds -->
`;
}

// ─── Architecture Templates ───

export function systemOverview(): string {
  return `# System Overview

> ⚠️ DRAFT — Describe the system architecture here.

## High-Level Architecture
<!-- Describe the overall system architecture -->

## Components
<!-- List and describe major components -->

## Data Flow
<!-- Describe how data flows through the system -->

## External Dependencies
<!-- List external services and dependencies -->
`;
}

export function components(): string {
  return `# Components

> ⚠️ DRAFT — Document the major components here.

## Component List
<!-- List each component with its responsibility -->

## Component Interactions
<!-- Describe how components interact -->

## Boundaries
<!-- Define component boundaries and interfaces -->
`;
}

// ─── Domain Templates ───

export function businessRules(): string {
  return `# Business Rules

> ⚠️ DRAFT — Document your business rules here.

## Core Rules
<!-- List the fundamental business rules -->

## Validation Rules
<!-- List input validation rules -->

## Authorization Rules
<!-- List access control rules -->
`;
}

export function workflows(): string {
  return `# Workflows

> ⚠️ DRAFT — Document your business workflows here.

## Core Workflows
<!-- Describe the main business workflows -->

## Edge Cases
<!-- Document known edge cases -->
`;
}

export function decisionTables(): string {
  return `# Decision Tables

> ⚠️ DRAFT — Document your decision logic here.

## Example Decision Table

| Condition A | Condition B | Result |
|-------------|-------------|--------|
| true        | true        | Allow  |
| true        | false       | Deny   |
| false       | *           | Deny   |
`;
}

export function scenariosYaml(): string {
  return `# Domain Scenarios
# These scenarios define expected behavior for critical domain logic.
# Use specman validate to verify scenarios match implementation.

scenarios:
  - id: EXAMPLE_SCENARIO
    description: Example scenario — replace with real scenarios
    input:
      condition_a: true
      condition_b: true
    expected:
      allowed: true
      reason: ALL_CONDITIONS_MET
`;
}

// ─── ADR Templates ───

export function adrTemplate(number: number, title: string): string {
  const paddedNum = String(number).padStart(4, '0');
  return `# ADR ${paddedNum}: ${title}

## Status
Proposed

## Context
<!-- Why this decision is needed -->

## Decision
<!-- What decision was made -->

## Consequences
<!-- Trade-offs and impact -->

## Related Specs
<!-- - specs/... -->
`;
}

export function initialAdr(): string {
  return adrTemplate(1, 'Initial Project Assumptions').replace(
    '<!-- Why this decision is needed -->',
    'This project was initialized with `specman init`. The detected stack and assumptions are based on auto-scanning the project structure.',
  ).replace(
    '<!-- What decision was made -->',
    'Accept the auto-generated assumptions as a starting point. All assumptions should be reviewed and approved before being treated as source of truth.',
  ).replace(
    '<!-- Trade-offs and impact -->',
    '- Auto-detection may miss technologies or generate incorrect assumptions\n- Manual review is required before approval\n- Approved specs become the source of truth for AI tools',
  );
}

// ─── Case Templates ───

export function casesReadme(): string {
  return `# Solved Cases

This directory contains previously solved problems, bugs, incidents, and their solutions.

## Purpose
- Capture institutional knowledge
- Help AI tools learn from past solutions
- Avoid repeating past mistakes

## Guidelines
- Keep cases concise and actionable
- Do NOT include secrets, raw production logs, or PII
- Add tags for easy searching
- Link to related specs when applicable

## Adding a Case

Create a new Markdown file in this directory using the case structure below. AI tools that read \`SPECMAN.md\` may create or update these files after solving meaningful project-specific issues.
`;
}

export function caseTemplate(title: string): string {
  return `# Case: ${title}

## Status
Draft

## Usage
- Times Used: 0
- Successful Uses: 0
- Score: 0

## Problem
<!-- Short description of the problem -->

## Context
<!-- Safe context only. Do not include secrets, customer data, private credentials, raw production logs, or PII. -->

## Root Cause
<!-- Why the issue happened -->

## Solution
<!-- What fixed it -->

## Files Changed
<!-- - path: short reason -->

## Validation
<!-- Commands/checks run and results -->

## Before
<!-- Optional safe snippet or summary -->

## After
<!-- Optional safe snippet or summary -->

## Result
<!-- Impact after the fix -->

## When To Reuse
<!-- When this solution pattern applies -->

## When NOT To Use
<!-- When this solution is unsafe, misleading, or not applicable -->

## Related Specs
<!-- - specs/... -->

## Tags
<!-- tag1, tag2 -->
`;
}

export function caseFromData(data: CaseData): string {
  const relatedSpecs = data.relatedSpecs.length > 0
    ? data.relatedSpecs.map(s => `- ${s}`).join('\n')
    : '<!-- No related specs -->';

  return `# Case: ${data.title}

## Status
${data.status}

## Usage
- Times Used: 0
- Successful Uses: 0
- Score: 0

## Problem
${data.problem}

## Context
${data.context}

## Root Cause
${data.rootCause}

## Solution
${data.solution}

## Files Changed
<!-- Not provided -->

## Validation
<!-- Not provided -->

## Before
${data.before || '<!-- Not provided -->'}

## After
${data.after || '<!-- Not provided -->'}

## Result
${data.result}

## When To Reuse
${data.whenToReuse}

## When NOT To Use
${data.whenNotToUse}

## Related Specs
${relatedSpecs}

## Tags
${data.tags.join(', ')}
`;
}

// ─── AI Templates ───

export function aiInstructions(): string {
  return `# AI Instructions

> ⚠️ DRAFT — These instructions guide AI coding tools working on this project.

## Before Coding
1. Read all files in \`specs/\` to understand the project context
2. Check \`specs/domain/\` for business rules that must not be violated
3. Check \`specs/adr/\` for architecture decisions
4. Search \`specs/cases/\` for related solved problems

## During Coding
- Follow approved specs as source of truth
- Follow coding rules in \`specs/engineering/\`
- Do not change architecture decisions unless explicitly asked
- Do not violate domain rules
- If a request conflicts with specs, stop and explain the conflict first

## After Coding
- If you solved a meaningful issue, create a solved case in \`specs/cases/\` using the standard case template.
- Do not store secrets or raw production logs in solved cases
`;
}

export function aiForbidden(): string {
  return `# Forbidden Patterns

> ⚠️ DRAFT — List patterns and practices that AI tools must avoid.

## Never Do
- Do not store secrets in code or specs
- Do not bypass authentication or authorization
- Do not ignore error handling
- Do not change domain rules without explicit approval
- Do not remove or weaken security controls
- Do not store PII or customer data in solved cases
- Do not store raw production logs in solved cases

## Avoid
- Avoid over-engineering simple solutions
- Avoid introducing new dependencies without justification
- Avoid breaking existing tests
`;
}

export function aiChecklist(): string {
  return `# AI Coding Checklist

> ⚠️ DRAFT — Checklist for AI tools before submitting code changes.

## Pre-Coding
- [ ] Read relevant specs
- [ ] Check domain rules
- [ ] Check ADRs
- [ ] Search solved cases

## During Coding
- [ ] Follow coding rules
- [ ] Follow testing rules
- [ ] Handle errors properly
- [ ] Do not violate domain rules

## Post-Coding
- [ ] Run tests
- [ ] Check for secrets
- [ ] Verify no spec conflicts
- [ ] Consider creating a solved case
`;
}

// ─── Domain Rule Template ───

export function domainRuleTemplate(name: string): string {
  return `# Domain Rule: ${name}

## Status
Draft

## Rule
<!-- Clear rule statement -->

## Rationale
<!-- Why this rule exists -->

## Examples
<!-- Input/output examples -->

## Edge Cases
<!-- Important edge cases -->

## Related Scenarios
<!-- - scenario id -->
`;
}

// ─── Spec Template ───

export function specTemplate(name: string): string {
  return `# ${name}

## Status
Draft

## Description
<!-- Describe this spec -->

## Details
<!-- Add details -->

## Related Specs
<!-- - specs/... -->
`;
}

// ─── .specmanignore Template ───

export function specmanIgnore(): string {
  return `# specman ignore patterns
# Files and directories matching these patterns will be excluded from scanning

node_modules/
dist/
build/
.git/
.env
.env.*
*.log
coverage/
__pycache__/
*.pyc
vendor/
target/
`;
}

// ─── Sync AI Instruction Templates ───

export function generateSpecmanMd(specsDir: string, approvalNote: string): string {
  return `# SPECMAN.md — Project Spec Protocol

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

This repository uses specman to keep specs, architecture decisions, domain rules, solved cases, and AI instructions consistent.

${coreInstructions(specsDir, approvalNote)}

## How To Use Specman

- Run \`specman init\` once to create the spec structure and AI tool rules.
- Run \`specman sync\` after changing specs so AI tool rules stay current.
- Run \`specman validate\` before finalizing meaningful changes.
- Run \`specman validate --logic\` when logic-lock is configured.
- Create solved cases in \`${specsDir}/cases/\` after meaningful fixes.
`;
}

function coreInstructions(specsDir: string, approvalNote: string): string {
  return `## Project Specs

${approvalNote}

## Before Making Any Code Changes

1. **Read the specs directory** (\`${specsDir}/\`) to understand the project context.
2. **Check domain rules** in \`${specsDir}/domain/\` — these must NEVER be violated.
3. **Check ADRs** in \`${specsDir}/adr/\` — follow existing architecture decisions.
4. **Search solved cases** in \`${specsDir}/cases/\` before solving similar problems.

## Critical Rules

- Treat approved specs as the **source of truth**.
- Treat unapproved specs as **draft assumptions only** — verify with the developer.
- **Do NOT change architecture decisions** unless explicitly asked by the developer.
- **Do NOT violate domain rules** under any circumstances.
- If a request **conflicts with specs**, stop and explain the conflict before proceeding.
- If solving a meaningful issue, **create a solved case in \`${specsDir}/cases/\` using the standard case template**.
- **Do NOT store secrets**, raw production logs, or PII in solved cases.

## Spec Structure

- \`${specsDir}/00-project-overview.md\` — Project overview
- \`${specsDir}/01-detected-stack.md\` — Technology stack
- \`${specsDir}/02-assumptions.md\` — Assumptions (check if approved)
- \`${specsDir}/03-open-questions.md\` — Open questions
- \`${specsDir}/product/\` — Product requirements
- \`${specsDir}/engineering/\` — Coding and testing rules
- \`${specsDir}/architecture/\` — System architecture and components
- \`${specsDir}/domain/\` — Business rules, workflows, decision tables, scenarios
- \`${specsDir}/adr/\` — Architecture Decision Records
- \`${specsDir}/cases/\` — Solved cases (previous problems and solutions)
- \`${specsDir}/ai/\` — AI-specific instructions, forbidden patterns, checklist

${caseCaptureProtocol(specsDir)}`;
}

function caseCaptureProtocol(specsDir: string): string {
  return `## Solved Case Capture Protocol

When you solve a meaningful problem, bug, incident, architecture issue, or recurring workflow issue, create a solved case file in \`${specsDir}/cases/\`.

Create a case when:
- The issue required non-obvious reasoning.
- The fix prevents a future regression.
- The solution documents a project-specific pattern.
- The work revealed a domain rule, architecture constraint, or operational lesson.

Do not create a case for:
- Trivial typo fixes.
- Pure formatting changes.
- Dependency bumps without behavior change.
- Temporary experiments.

Before writing the case:
1. Redact secrets, tokens, passwords, customer data, raw production logs, and PII.
2. Prefer summaries over raw logs.
3. Link related specs, ADRs, domain rules, tests, and changed files.

When reusing an existing case:
1. Prefer cases whose problem/context matches the current issue.
2. Increment \`Times Used\` when the case informed your approach.
3. Increment \`Successful Uses\` and \`Score\` when the case helped solve the problem.
4. Mention the reused case path in your final response.

Filename:
\`${specsDir}/cases/YYYY-MM-DD-kebab-case-title.md\`

Template:
\`\`\`md
# Case: <title>

## Status
Draft

## Usage
- Times Used: 0
- Successful Uses: 0
- Score: 0

## Problem
<What happened or what needed solving>

## Context
<Project-safe context only. No secrets, PII, or raw production logs.>

## Root Cause
<Why it happened>

## Solution
<What changed and why>

## Files Changed
- \`<path>\`: <short reason>

## Validation
- <test/check/build command and result>

## When To Reuse
<When this solution pattern applies>

## When NOT To Use
<When this solution would be wrong or risky>

## Related Specs
- \`${specsDir}/...\`

## Tags
<tag1>, <tag2>
\`\`\`

After creating the case:
- Mention the new case path in your final response.
- If unsure whether a case is worth creating, ask first.`;
}

export function generateClaudeMd(specsDir: string, approvalNote: string): string {
  return `# CLAUDE.md — Project Instructions for Claude

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Claude-Specific Instructions

- Read this entire file before starting any task.
- Summarize the relevant domain rules and ADRs before writing code.
- When in doubt about a domain rule, ask the developer rather than guessing.
- Prefer reading specs over inferring from code — specs are the source of truth.
`;
}

export function generateAgentsMd(specsDir: string, approvalNote: string): string {
  return `# AGENTS.md — Project Instructions for AI Agents

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Agent-Specific Instructions

- Read the full spec directory before starting work.
- If you are unsure about a spec, ask the developer.
- Always verify your changes against domain rules.
- Run relevant tests after making changes.
`;
}

export function generateCodexMd(specsDir: string, approvalNote: string): string {
  return `# CODEX.md — Project Instructions for Codex

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Codex-Specific Instructions

- Read relevant spec files before implementing changes.
- Follow domain rules and ADRs strictly.
- Call out spec conflicts explicitly before proceeding.
- Suggest spec updates when behavior changes.
`;
}

export function generateCursorRules(specsDir: string, approvalNote: string): string {
  return `---
description: Project specs and rules managed by specman
globs:
  - "**/*"
alwaysApply: true
---

# Specman Project Rules

> This file was auto-generated by \`specman sync\`. Do not edit manually.

${coreInstructions(specsDir, approvalNote)}

## Cursor-Specific Instructions

- Always read relevant spec files before suggesting code changes.
- Highlight any conflicts between requested changes and existing specs.
- Suggest updating specs when code changes affect architecture or domain rules.
`;
}

export function generateCopilotInstructions(specsDir: string, approvalNote: string): string {
  return `# Copilot Instructions

> This file was auto-generated by \`specman sync\`. Do not edit manually.
> Regenerate with \`specman sync\` after updating specs.

${coreInstructions(specsDir, approvalNote)}

## Copilot-Specific Instructions

- Prefer patterns that align with the project's coding rules.
- Follow the architecture described in specs.
- Do not suggest changes that violate domain rules.
`;
}
