import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { initCommand } from '../../src/commands/init.js';
import { removeCommand } from '../../src/commands/remove.js';
import { fileExists } from '../../src/core/files.js';

describe('remove command', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), 'specman-remove-'));
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  it('should preview removals without deleting by default', async () => {
    await initCommand(tempDir);

    await removeCommand(tempDir);

    expect(await fileExists(join(tempDir, 'specs'))).toBe(true);
    expect(await fileExists(join(tempDir, '.specman'))).toBe(true);
  });

  it('should remove specman-managed files when confirmed', async () => {
    await initCommand(tempDir);

    await removeCommand(tempDir, { yes: true });

    expect(await fileExists(join(tempDir, 'specs'))).toBe(false);
    expect(await fileExists(join(tempDir, '.specman'))).toBe(false);
    expect(await fileExists(join(tempDir, '.specmanignore'))).toBe(false);
  });

  it('should not remove user-authored AI instruction files', async () => {
    await initCommand(tempDir);
    await writeFile(join(tempDir, 'CLAUDE.md'), '# Manual Claude Instructions\n', 'utf-8');
    await writeFile(join(tempDir, 'AGENTS.md'), '# Manual Agent Instructions\n', 'utf-8');

    await removeCommand(tempDir, { yes: true });

    expect(await fileExists(join(tempDir, 'CLAUDE.md'))).toBe(true);
    expect(await fileExists(join(tempDir, 'AGENTS.md'))).toBe(true);
  });

  it('should remove generated AI instruction files with specman marker', async () => {
    await initCommand(tempDir);
    await writeFile(join(tempDir, 'SPECMAN.md'), 'auto-generated by `specman sync`\n', 'utf-8');

    await removeCommand(tempDir, { yes: true });

    expect(await fileExists(join(tempDir, 'SPECMAN.md'))).toBe(false);
  });

  it('should strip managed blocks without deleting user-authored AI instruction files', async () => {
    await initCommand(tempDir);
    await writeFile(
      join(tempDir, 'CLAUDE.md'),
      '# Manual Claude Instructions\n\n<!-- specman:start -->\nauto-generated by `specman sync`\n<!-- specman:end -->\n',
      'utf-8',
    );

    await removeCommand(tempDir, { yes: true });

    expect(await fileExists(join(tempDir, 'CLAUDE.md'))).toBe(true);
    expect(await readFile(join(tempDir, 'CLAUDE.md'), 'utf-8')).toBe('# Manual Claude Instructions\n');
  });
});
