import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { initCommand } from '../../src/commands/init.js';
import { syncCommand } from '../../src/commands/sync.js';
import { fileExists } from '../../src/core/files.js';

describe('sync command', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), 'specman-sync-'));
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  it('should generate CODEX.md when codex tool is enabled', async () => {
    await initCommand(tempDir);

    const statusPath = join(tempDir, '.specman', 'status.json');
    const status = JSON.parse(await readFile(statusPath, 'utf-8'));
    status.approved = true;
    status.approvedAt = '2026-01-01T00:00:00.000Z';
    status.approvedBy = 'tester';
    await writeFile(statusPath, JSON.stringify(status, null, 2) + '\n', 'utf-8');

    const configPath = join(tempDir, '.specman', 'config.json');
    const config = JSON.parse(await readFile(configPath, 'utf-8'));
    config.aiTools = {
      claude: false,
      codex: true,
      agents: false,
      cursor: false,
      copilot: false,
    };
    await writeFile(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
    await rm(join(tempDir, 'CLAUDE.md'), { force: true });
    await rm(join(tempDir, 'AGENTS.md'), { force: true });
    await rm(join(tempDir, 'CODEX.md'), { force: true });

    await syncCommand(tempDir, 'all');

    expect(await fileExists(join(tempDir, 'CODEX.md'))).toBe(true);
    expect(await fileExists(join(tempDir, 'CLAUDE.md'))).toBe(false);
    expect(await fileExists(join(tempDir, 'AGENTS.md'))).toBe(false);
  });

  it('should append managed block to user-authored files when confirmed', async () => {
    await initCommand(tempDir);
    await writeFile(join(tempDir, 'CLAUDE.md'), '# My Claude Rules\n', 'utf-8');

    await syncCommand(tempDir, 'all', { yes: true });

    const content = await readFile(join(tempDir, 'CLAUDE.md'), 'utf-8');
    expect(content).toContain('# My Claude Rules');
    expect(content).toContain('<!-- specman:start -->');
    expect(content).toContain('<!-- specman:end -->');
  });

  it('should not change user-authored files without confirmation', async () => {
    await initCommand(tempDir);
    await writeFile(join(tempDir, 'CLAUDE.md'), '# My Claude Rules\n', 'utf-8');

    await syncCommand(tempDir, 'all');

    const content = await readFile(join(tempDir, 'CLAUDE.md'), 'utf-8');
    expect(content).toBe('# My Claude Rules\n');
  });

  it('should replace existing managed blocks instead of duplicating them', async () => {
    await initCommand(tempDir);
    await writeFile(
      join(tempDir, 'CLAUDE.md'),
      '# My Claude Rules\n\n<!-- specman:start -->\nold\n<!-- specman:end -->\n\n<!-- specman:start -->\nduplicate\n<!-- specman:end -->\n',
      'utf-8',
    );

    await syncCommand(tempDir, 'all');

    const content = await readFile(join(tempDir, 'CLAUDE.md'), 'utf-8');
    expect(content.match(/<!-- specman:start -->/g)).toHaveLength(1);
    expect(content).toContain('# My Claude Rules');
    expect(content).not.toContain('duplicate');
  });

  it('should report pending changes in check mode', async () => {
    await initCommand(tempDir);
    await rm(join(tempDir, 'CLAUDE.md'), { force: true });

    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => {
      throw new Error('process.exit called');
    });
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});

    await expect(syncCommand(tempDir, 'all', { check: true })).rejects.toThrow('process.exit called');
    expect(exitSpy).toHaveBeenCalledWith(1);
    const output = logSpy.mock.calls.flat().join('\n');
    expect(output).toContain('CLAUDE.md');

    logSpy.mockRestore();
    exitSpy.mockRestore();
  });

  it('should pass check mode when generated files are current', async () => {
    await initCommand(tempDir);

    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => {
      throw new Error('process.exit called');
    });
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});

    await syncCommand(tempDir, 'all', { check: true });

    expect(exitSpy).not.toHaveBeenCalled();
    const output = logSpy.mock.calls.flat().join('\n');
    expect(output).toContain('SPECMAN.md');

    logSpy.mockRestore();
    exitSpy.mockRestore();
  });

  it('should migrate legacy generated files to managed blocks', async () => {
    await initCommand(tempDir);
    await writeFile(join(tempDir, 'CLAUDE.md'), 'auto-generated by `specman generate --target ai`\nlegacy\n', 'utf-8');

    await syncCommand(tempDir, 'all');

    const content = await readFile(join(tempDir, 'CLAUDE.md'), 'utf-8');
    expect(content).toContain('<!-- specman:start -->');
    expect(content).toContain('auto-generated by `specman sync`');
    expect(content).not.toContain('legacy');
  });

  it('should not generate CODEX.md when codex tool is disabled', async () => {
    await initCommand(tempDir);

    const configPath = join(tempDir, '.specman', 'config.json');
    const config = JSON.parse(await readFile(configPath, 'utf-8'));
    config.aiTools.codex = false;
    await writeFile(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
    await rm(join(tempDir, 'CODEX.md'), { force: true });

    await syncCommand(tempDir, 'all');

    expect(await fileExists(join(tempDir, 'CODEX.md'))).toBe(false);
  });

  it('should exit for unknown target', async () => {
    await initCommand(tempDir);

    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => {
      throw new Error('process.exit called');
    });

    await expect(syncCommand(tempDir, 'codex')).rejects.toThrow('process.exit called');
    expect(exitSpy).toHaveBeenCalledWith(1);

    exitSpy.mockRestore();
  });
});
